In [1]:

import pandas as pd
import numpy as np
import yfinance as yf
import datetime
import MetaTrader5 as mt
import pytz
import importlib

import data as d
import functions as f
import main as m

C:\Users\ariad\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)

In [2]:
def historico(ticker):
#del archivo donde estan los datos de inicio de sesión
    param_archivo = pd.read_csv(r'C:\Users\ariad\OneDrive\Documentos\GitHub\myst_proyecto_1\files\cuentas.csv')
    Names = list(param_archivo['Name'])
    Users = list(param_archivo['Account'])
    Passwords = list(param_archivo['Password'])
    
    #iniciar conexión con MT5
    mt.initialize(login=Users[0], server='FxPro-MT5',password=Passwords[0])
    if not mt.initialize(): 
        print("initialize() failed, error code =",mt.last_error()) 
        quit() 
    # establecemos el huso horario en UTC 
    timezone = pytz.timezone("Etc/UTC") 
    # creamos el objeto datetime en el huso horario UTC, para que no se aplique el desplazamiento del huso horario local 
    date_from = datetime.datetime(2018, 1, 1, tzinfo=timezone)
    date_to = datetime.datetime(2020,3,1,tzinfo=timezone) 
    # obtenemos 10 barras de EURUSD H4 a partir del 01.10.2020 en el huso horario UTC 
    rates = mt.copy_rates_range(ticker, mt.TIMEFRAME_M15, date_from, date_to) 
    
    # finalizamos la conexión con el terminal MetaTrader 5 
    mt.shutdown() 
    # creamos un DataFrame de los datos obtenidos 
    rates_frame = pd.DataFrame(rates) 
    # convertimos la hora en segundos al formato datetime 
    rates_frame['time']=pd.to_datetime(rates_frame['time'], unit='s')              
    # mostramos los datos  
    return rates_frame
   
   
divisa = historico('EURUSD') #prueba

print(divisa.tail())
print(divisa.head())

                     time     open     high      low    close  tick_volume  \
53583 2020-02-28 22:45:00  1.10445  1.10446  1.10328  1.10371        12727
53584 2020-02-28 23:00:00  1.10372  1.10424  1.10232  1.10279         8632
53585 2020-02-28 23:15:00  1.10279  1.10318  1.10261  1.10305         3709
53586 2020-02-28 23:30:00  1.10305  1.10394  1.10302  1.10309         4400
53587 2020-02-28 23:45:00  1.10309  1.10320  1.10233  1.10262         4538

       spread  real_volume
53583      15   1909050000
53584      15   1294800000
53585      15    556350000
53586      15    660000000
53587      13    680700000
                 time     open     high      low    close  tick_volume  \
0 2018-01-02 00:00:00  1.20087  1.20095  1.20007  1.20090          705
1 2018-01-02 00:15:00  1.20090  1.20094  1.20034  1.20058         1083
2 2018-01-02 00:30:00  1.20059  1.20160  1.20058  1.20135          969
3 2018-01-02 00:45:00  1.20135  1.20141  1.20125  1.20130         1234
4 2018-01-02 01:00:00  1.20130  1.20139  1.20019  1.20137         4787

   spread  real_volume
0      16    155200000
1      19    216600000
2      18    193800000
3      20    246800000
4      18    957400000

In [3]:
d.indice

     index            DateTime  Actual  Consensus  Previous
0      110 2018-01-03 21:30:00  -4.992     -6.000    -6.000
1      109 2018-01-09 21:30:00 -11.190     -4.992    -4.992
2      108 2018-01-17 21:30:00  -5.121    -11.190   -11.190
3      107 2018-01-23 21:30:00   4.755     -5.121    -5.121
4      106 2018-01-30 21:30:00   3.229      4.755     4.755
..     ...                 ...     ...        ...       ...
106      4 2020-01-14 21:30:00   1.100     -5.945    -5.945
107      3 2020-01-22 21:30:00   1.600      1.100     1.100
108      2 2020-01-28 21:30:00  -4.270      1.600     1.600
109      1 2020-02-04 21:30:00   4.180     -4.270    -4.270
110      0 2020-02-11 21:30:00   6.000      4.180     4.180

[111 rows x 5 columns]

In [4]:
df_index = f.clas_esc(d.indice)
df_index

C:\Users\ariad\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
c:\Users\ariad\OneDrive\Documentos\GitHub\myst_proyecto_1\functions.py:34: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_indice.Operacion[i] = 'Sell'
c:\Users\ariad\OneDrive\Documentos\GitHub\myst_proyecto_1\functions.py:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_indice.Operacion[i] = 'Buy'

,index,DateTime,Actual,Consensus,Previous,Escenario,Operacion
0,110,2018-01-03 21:30:00,-4.992,-6.000,-6.000,A,Sell
1,109,2018-01-09 21:30:00,-11.190,-4.992,-4.992,C,Buy
2,108,2018-01-17 21:30:00,-5.121,-11.190,-11.190,A,Sell
3,107,2018-01-23 21:30:00,4.755,-5.121,-5.121,A,Sell
4,106,2018-01-30 21:30:00,3.229,4.755,4.755,C,Buy
...,...,...,...,...,...,...,...
106,4,2020-01-14 21:30:00,1.100,-5.945,-5.945,A,Sell
107,3,2020-01-22 21:30:00,1.600,1.100,1.100,A,Sell
108,2,2020-01-28 21:30:00,-4.270,1.600,1.600,C,Buy
109,1,2020-02-04 21:30:00,4.180,-4.270,-4.270,A,Sell
110,0,2020-02-11 21:30:00,6.000,4.180,4.180,A,Sell

In [26]:
fechas = []
actual = []
prevision = []
anterior = [] 
escenario = []
signo = []
direccion = []
pip =.0001
trading = 100
pip_alcista = []
pip_bajista = []
volatilidad = []
for i in range(len(d.divisa)):
    for j in range(len(df_index)):
        if df_index['DateTime'][j]==d.divisa.time[i]:
            fechas.append(df_index.DateTime[j])
            actual.append(df_index.Actual[j])
            prevision.append(df_index.Consensus[j])
            anterior.append(df_index.Previous[j])
            escenario.append(df_index.Escenario[j])
            # dirección 
            if df_index['Operacion'][j] == 'Sell':
                direccion.append(-1)

            elif df_index['Operacion'][j] == 'Buy':
                direccion.append(1)
            # pips Alcistas
            pip_alcista.append(abs(np.round((d.divisa.high[i-15]-d.divisa.high[i+15])-d.divisa.open[i-15])))
            #pip_alcista.append(abs(((pip*trading)/d.divisa.open[i]*1000)))
            # pips Bajistas
            pip_bajista.append(abs(np.round((d.divisa.open[i-15]-d.divisa.low[i+15])*1000)))
            #pip_bajista.append(abs(((pip*trading)/d.divisa.close[i])*1000))
            # volatilidad 
            volatilidad.append(np.round(abs((d.divisa.high[i-15]- d.divisa.high[i+15])-(d.divisa.low[i-15]- d.divisa.low[i+15]))*10000))

In [25]:
pip_bajista

[]

In [46]:
a = d.indice['DateTime'][0] == d.divisa.time[0]
a

False

In [39]:

d.divisa.time

0       2018-01-02 00:00:00
1       2018-01-02 00:15:00
2       2018-01-02 00:30:00
3       2018-01-02 00:45:00
4       2018-01-02 01:00:00
                ...
53583   2020-02-28 22:45:00
53584   2020-02-28 23:00:00
53585   2020-02-28 23:15:00
53586   2020-02-28 23:30:00
53587   2020-02-28 23:45:00
Name: time, Length: 53588, dtype: datetime64[ns]

In [8]:
importlib.reload(f)

**Backtest**

In [9]:
df_index = f.clas_esc(d.indice)
df_index.head(7)

C:\Users\ariad\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
c:\Users\ariad\OneDrive\Documentos\GitHub\myst_proyecto_1\functions.py:34: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_indice.Operacion[i] = 'Sell'
c:\Users\ariad\OneDrive\Documentos\GitHub\myst_proyecto_1\functions.py:36: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_indice.Operacion[i] = 'Buy'

             DateTime  Actual  Consensus  Previous Escenario Operacion
0 2018-01-03 21:30:00  -4.992     -6.000    -6.000         A      Sell
1 2018-01-09 21:30:00 -11.190     -4.992    -4.992         C       Buy
2 2018-01-17 21:30:00  -5.121    -11.190   -11.190         A      Sell
3 2018-01-23 21:30:00   4.755     -5.121    -5.121         A      Sell
4 2018-01-30 21:30:00   3.229      4.755     4.755         C       Buy
5 2018-02-06 21:30:00  -1.050      3.229     3.229         C       Buy
6 2018-02-13 21:30:00   3.940     -1.050    -1.050         A      Sell

In [11]:
df_backtest = pd.DataFrame()
df_backtest['DateTime'] = df_index.DateTime 
df_backtest['escenario'] = df_index.Escenario
df_backtest['operacion'] = df_index.Operacion
df_backtest['volumen'] = 100
df_backtest

               DateTime escenario operacion  volumen
0   2018-01-03 21:30:00         A      Sell      100
1   2018-01-09 21:30:00         C       Buy      100
2   2018-01-17 21:30:00         A      Sell      100
3   2018-01-23 21:30:00         A      Sell      100
4   2018-01-30 21:30:00         C       Buy      100
..                  ...       ...       ...      ...
106 2020-01-14 21:30:00         A      Sell      100
107 2020-01-22 21:30:00         A      Sell      100
108 2020-01-28 21:30:00         C       Buy      100
109 2020-02-04 21:30:00         A      Sell      100
110 2020-02-11 21:30:00         A      Sell      100

[111 rows x 4 columns]